includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12.yaml

data_root: D:/codes/NJU/Third_Year/ml/BigHomework/cifar10
image_size: 32
  
save_path: ./
# data
init_cls_num: 2
inc_cls_num: 2
task_num: 5


epoch: 3
device_ids: 0
n_gpu: 1
val_per_epoch: 1

optimizer:
  name: SGD
  kwargs:
    lr: 0.1

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.1
    step_size: 10

backbone:
  name: resnet18
  kwargs:
    num_classes: 10
    args: 
      dataset: cifar10


buffer:
  name: LinearHerdingBuffer
  kwargs:
    buffer_size: 500
    batch_size: 32
    # strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: ICarl
  kwargs:
    num_class: 10
    feat_dim: 512
